r"""Count charge/discharge cycles in a battery current profile and age the capacity.

The counter walks the current signal sample by sample and looks for two
independent events:

* a **current sign change** - the cell switches between charging and
  discharging;
* a **charge sign change** - the integrated charge crosses the level it
  started the cycle at.

One cycle of the shape generated by ``cycle_generator.py``::

    SoC   /\
         /  \
             \    /
              \  /
               \/

    I   ___      ___
           |    |
           |____|

produces two current sign changes and three charge crossings. Requiring both
counts is what lets a shallow cycle and a deep cycle be told apart when they
are interleaved: the current alone looks identical, only the charge excursion
differs.

Every counted cycle yields its depth of discharge (DoD), which is converted
into equivalent full cycles and used to age the nominal capacity.

Running this module reads ``aging_profile.csv`` and writes ``CN_evolution.png``.
"""

import argparse
import csv
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np

CAPACITY_AS = 7200.0  # Nominal capacity C_N in ampere seconds (2 Ah)
SAMPLE_TIME_S = 10.0
PROFILE_CSV = Path("aging_profile.csv")

# Aging model: end of life is 80 % of the nominal capacity. Reaching it takes
# 2000 full cycles, but only 1400 equivalent full cycles when they are made of
# 20 % partial cycles - shallow cycling is gentler per unit of throughput.
FULL_CYCLE_FADE = 0.20 / 2000  # Capacity loss per equivalent full cycle
PARTIAL_CYCLE_FADE = 0.05 / 1400
PARTIAL_CYCLES_PER_EQUIVALENT = 5  # Five 20 % cycles make one full cycle

DOD_TOLERANCE = 1e-6


class CycleCounter:
    """Stateful cycle counter over a current profile.

    The counter keeps its position in the profile between calls, so repeated
    calls to :meth:`count_cycle` walk forward through the signal.
    """

    def __init__(self, capacity=CAPACITY_AS):
        self.capacity = capacity  # Nominal capacity in As
        self.n_cycles = 0  # Cycles counted so far
        self.idx = 0  # Position in the profile

    def count_cycle(self, charge_init, current_profile, ts):
        """Advance to the end of the next complete cycle.

        Returns ``(n_cycles, dod, charge)`` or ``None`` when the profile runs
        out before the cycle closes. The trailing partial cycle is deliberately
        not counted: its depth is unknown, and guessing it would bias the
        aging result.
        """
        charge = charge_init
        discharged = 0.0  # Negative charge throughput of this cycle

        current_sign = np.sign(current_profile[self.idx])
        charge_sign = current_sign

        current_sign_changes = 0
        charge_sign_changes = 0

        for offset, current in enumerate(current_profile[self.idx :]):
            if np.sign(current) == -1:
                discharged += current * ts  # Accumulate DoD

            charge += current * ts

            if np.sign(current) != current_sign:
                current_sign = np.sign(current)
                current_sign_changes += 1

            if np.sign(charge - charge_init) != charge_sign:
                charge_sign = np.sign(charge - charge_init)
                charge_sign_changes += 1

            if current_sign_changes >= 2 and charge_sign_changes >= 3:
                self.n_cycles += 1
                self.idx += offset + 1
                return self.n_cycles, abs(discharged / self.capacity), charge

        self.idx = len(current_profile)  # Profile exhausted mid cycle
        return None


def reduce_capacity(capacity, cycle_type, n_cycles, capacity_init, buggy=False):
    """Apply one step of capacity fade.

    ``buggy=True`` reproduces a mistake students reliably make: indexing the
    aging curve with the *faded* capacity and the absolute cycle count, which
    re-reads the lookup table from a moving origin. The fade then compounds and
    the capacity curve bends away from the straight reference line.
    """
    fade = {"full": FULL_CYCLE_FADE, "partial": PARTIAL_CYCLE_FADE}.get(cycle_type)
    if fade is None:
        raise ValueError(f"unknown cycle type: {cycle_type!r}")

    if buggy:
        return capacity_init - capacity * fade * n_cycles
    return capacity - capacity_init * fade


def load_profile(path=PROFILE_CSV):
    """Read a two column csv written by ``cycle_generator.save_profile``."""
    with open(path) as handle:
        rows = list(csv.reader(handle))[1:]  # Skip header
    time = np.array([float(row[0]) for row in rows])
    current = np.array([float(row[1]) for row in rows])
    return time, current


def count_profile(current, ts=SAMPLE_TIME_S, capacity=CAPACITY_AS, buggy=False):
    """Count every complete cycle in ``current`` and track the capacity fade.

    Returns the cycle tallies and the capacity trace over equivalent full
    cycles.
    """
    counter = CycleCounter(capacity)
    charge = 0.5 * capacity  # Start at mid SoC, like the generated profile
    full_cycles = 0
    partial_cycles = 0
    equivalent_full_cycles = 0
    capacity_log = []

    while counter.idx < len(current):
        result = counter.count_cycle(charge, current, ts)
        if result is None:
            break
        _, dod, charge = result

        if np.isclose(dod, 1.0, atol=DOD_TOLERANCE):
            full_cycles += 1
            equivalent_full_cycles += 1
            capacity = reduce_capacity(
                capacity, "full", equivalent_full_cycles, CAPACITY_AS, buggy
            )
            capacity_log.append(capacity)
        elif np.isclose(dod, 0.2, atol=DOD_TOLERANCE):
            partial_cycles += 1
            # Only a whole equivalent full cycle moves the aging model.
            if partial_cycles % PARTIAL_CYCLES_PER_EQUIVALENT == 0:
                equivalent_full_cycles += 1
                capacity = reduce_capacity(
                    capacity, "partial", equivalent_full_cycles, CAPACITY_AS, buggy
                )
                capacity_log.append(capacity)
        else:
            raise ValueError(f"undefined cycle depth: DoD={dod}")

    return full_cycles, partial_cycles, equivalent_full_cycles, np.array(capacity_log)


def plot_capacity(
    capacity_log, full_cycles, partial_cycles, equivalent_full_cycles, output
):
    """Plot the capacity trace against the ideal straight fade line."""
    reference = CAPACITY_AS * (1 - FULL_CYCLE_FADE * np.arange(len(capacity_log)))

    fig, ax = plt.subplots(figsize=(6, 6))
    ax.plot(capacity_log, label="capacity")
    ax.plot(reference, "--", linewidth=0.5, label="reference")
    ax.set(
        xlabel="Equivalent full cycles",
        ylabel="Capacity (As)",
        title="Capacity Evolution",
    )
    ax.text(
        0.05,
        0.05,
        f"full cycles: {full_cycles}\n"
        f"20 % cycles: {partial_cycles}\n"
        f"equivalent full cycles: {equivalent_full_cycles}",
        transform=ax.transAxes,
    )
    ax.legend()
    fig.tight_layout()
    fig.savefig(output)


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--buggy",
        action="store_true",
        help="use the wrong aging lookup (see reduce_capacity) to show the effect",
    )
    args = parser.parse_args()

    _, current = load_profile()
    full, partial, equivalent, capacity_log = count_profile(current, buggy=args.buggy)

    output = "CN_evolution_buggy.png" if args.buggy else "CN_evolution.png"
    plot_capacity(capacity_log, full, partial, equivalent, output)

    print("Counted full cycles:      ", full)
    print("Counted 20 % cycles:      ", partial)
    print("Equivalent full cycles:   ", equivalent)
    print(f"Remaining capacity:        {capacity_log[-1]:.1f} As")
    print(f"Plot written to            {output}")


if __name__ == "__main__":
    main()
